# creates a Minimum Spanning Tree (MST)
# based on vcf-table generated by parSNP pipeline

### load needed libraries

library(tidyverse) # also loads dplyr, tidy and stats package
library(phangorn) # used for phyDat object, also loads ape package
library(ggtree)
library(phytools)

library(devEMF)

################################################################################
### generating data

# load-vcf-Table generated by parSNP
x <- read.delim2(file.choose(), na.strings=c("NULL","NA", ""), skip = 9, header=TRUE, sep ="\t")

# change table from list to dataframe and remove unwanted columns
df <- as.data.frame(x)
drops <- c("X.CHROM","ID", "QUAL", "REF", "ALT", "FILTER", "INFO", "FORMAT")
df_subset <- df[ ,!(names(df) %in% drops)]

# parsing of dataframe (combine unique columns)
t1 <- as.data.frame(t(df_subset))
t2<- mutate(t1,ID = row.names(t1))

t2Cols <- ncol(t2)
t3 <- aggregate(t2[t2Cols], t2[-t2Cols], 
                FUN = function(X) paste(unique(X), collapse="\n"))

row.names(t3) <- t3$ID
t4 <- select(t3, - ID)
t5 <- as.data.frame(t(t4))
t6 <- select(t5, - POS)
variations <- t6    #<- new variations matrix
variations <- t(variations)
rownames(variations)<-gsub("\\.f.+","",rownames(variations))

# generate a phyDat object (keep only lvls 1 and 0 to use binary system)
# lvls above will be discarded
variations_phyDat <- phyDat(variations, type = "USER", levels = c(1,0))

# create distance matrix
#dna_dist <- dist(variations, method = "binary")

################################################################################
### plotting

# UPGMA-calculation and tree
#variations_UPGMA <- upgma(dna_dist)
#plot(variations_UPGMA, main="UPGMA")

# build parsimony tree
treeRatchet  <- pratchet(variations_phyDat, trace = 0)
treeRatchet  <- acctran(treeRatchet, variations_phyDat)

# saving tree in newick format for MST Online building tool
# https://achtman-lab.github.io/GrapeTree/MSTree_holder.html
ape::write.tree(treeRatchet, file="MST.txt")


###############

# only for building maximum likelihood tree

#Load alignment file
alignmentfile <- read.dna(file.choose(), format="fasta")
alignment_phyDat <- phyDat(alignmentfile, type = "DNA", levels = NULL)

#Modeltest
mt <- modelTest(alignment_phyDat)
fit_mt <- pml_bb(mt, control = pml.control(trace = 0))

#Bootstrap
bs <- bootstrap.pml(fit_mt, bs=500, optNni=TRUE,
                    control = pml.control(trace = 0))

#Building and saving tree
ggsave("V770_mlh.pdf", width = 50, height = 50, units = "cm", limitsize = FALSE)
emf(file = "v770_mlh.emf", width = 10, height = 10,bg = "transparent", pointsize = 12,family = "Helvetica", coordDPI = 600)
plotBS(midpoint(fit_mt$tree), bs, p = 50, type="p", main="Standard bootstrap")
plotBS(midpoint(fit_mt$tree), bs, p = 100, type="p", main="Standard bootstrap")
dev.off()

###############

p <- plotTree(treeRatchet)
edgelabels(cex = 0.6, frame = 'n', adj = c(1, -1))

# MST-like-Plot
edge <- data.frame(treeRatchet$edge, edge_num=1:nrow(treeRatchet$edge), round(treeRatchet$edge.length,1))
colnames(edge) <- c("parent", "node", "edge_num", "edge_length")

# modify all(!) length in order to obtain positive values for log-transformation
edge$edge_length_mod <- edge$edge_length + 1.1

# log-transformation
treeRatchet$edge.length <- log(edge$edge_length_mod)

# write new genomes in a group to color them
treeRatchet <- groupOTU(treeRatchet, c("MH_JJ", "MH_VW", "MH_MFM", "MH_PR"))

# first MST plot
p <- ggtree(treeRatchet, layout="daylight") +
        geom_tippoint(size=10, fill="grey", color="black", shape=21) +
        geom_tiplab2(align=FALSE, hjust = -0.38, nudge_x = -0.1, angle = 0, aes(color=group)) +
        scale_color_manual(values=c("black", "red")) + 
        theme(legend.position = "none") + 
        coord_cartesian(clip = 'off') + 
        theme_tree2(plot.margin=margin(6, 120, 20, 40))

p %<+% edge + geom_label(aes(x=branch, label=edge_length, vjust = -0.2, hjust=0.5))
p %<+% edge + geom_text(aes(x=branch, label=node))

################################################################################
### improve first tree

# get the node/tip positions
newaes <- as.data.frame(p$data)

# labeling and new layer
newaes2 <- data.frame()
for(i in 1:max(newaes$node)){
        xlabel = mean(c(newaes[newaes$node == i,]$x,newaes[newaes$node == (newaes[newaes$node == i,]$parent),]$x))      
        ylabel = mean(c(newaes[newaes$node == i,]$y,newaes[newaes$node == (newaes[newaes$node == i,]$parent),]$y))
        newaes3 <- c(xlabel,ylabel,edge[edge$node == i,]$edge_length )
        newaes2 <- rbind(newaes2, newaes3)
}
colnames(newaes2) <- c("xlabel", "ylabel", "edge_length")

newaes2 <- newaes2[newaes2$edge_length>0,]
newaes2$edge_length <- round(newaes2$edge_length)

# build new dataframe for labeling
edgenew <- data.frame(
        xpos = as.vector(newaes2$xlabel),
        ypos =  as.vector(newaes2$ylabel),
        hjustvar = +0.5,
        vjustvar = +0.5,
        annotateText = as.vector(newaes2$edge_length)
)

par(mar=c(0,0,0,0))

# modify above MST with new input
p %<+%  edge + 
  geom_label(data=edgenew,aes(x=xpos,y=ypos,hjust=hjustvar,vjust=vjustvar,label=annotateText),
             fill = "white", label.size = NA, label.padding = unit(0.1, "lines"))

################################################################################

# Plotten
ggsave("V770_mst.pdf", width = 50, height = 50, units = "cm", limitsize = FALSE)
svg("V770_mst.svg", width= 10, height = 10)
emf(file = "V770_mst.emf", width = 10, height = 10,bg = "transparent", pointsize = 12,family = "Helvetica", coordDPI = 600)

dev.off()
################################################################################